import '../../marktang/lib/codemirror/lib/codemirror.css';
import '../../marktang/lib/highlight/styles/monokai_sublime.css';
import '../../marktang/lib/codemirror/theme/ryan-dark.css';
import '../../stylesheets/flymarkdown.less';

import '../../libs/jquery.min.js';
import 'highlight.js';
import 'moment';
// import 'remarkable';
// import '../../marktang/lib/highlight.min.js';
import '../../libs/jsface.min.js';
// import '../../libs/moment.min.js';
import '../../libs/lodash.compat.min.js';
// import '../../libs/remarkable.js';
import '../../libs/webuploader/webuploader.withoutimage.js';
import 'codemirror';
// import '../../marktang/lib/codemirror/lib/codemirror.js';
import '../../marktang/lib/marked.js';
// import '../../marktang/lib/mathjax/MathJax.js';
// import '../../marktang/lib/codemirror/addon/mode/overlay.js';
// import '../../marktang/lib/codemirror/mode/xml/xml.js';
// import '../../marktang/lib/codemirror/mode/markdown/markdown.js';
// import '../../marktang/lib/codemirror/mode/gfm/gfm.js';
// import '../../marktang/lib/codemirror/mode/javascript/javascript.js';
import '../../javascripts/config.js';
import '../../javascripts/utils.js';
import '../../marktang/js/flymarkdown.js?v=1.1';
import '../../javascripts/ui.js';
import '../../javascripts/main.js';
import '../../javascripts/draft-autosave.js';